### ISSUE TITLE
Stolen Content

### ISSUE THREAD

**Issue by drewstephensdesigns** [davesc63/GeoPort#121]
This individual decomplied your source code and is now posting about it on Reddit.

https://github.com/Nightmaresuwu/GeoPort-Decompyled

**Comment by Nightmaresuwu** [comment]
💀

**Comment by davesc63** [comment]
Yeah. Can’t please everyone. But the plus side. Since adding the code we’ve had more GitHub stars and donations,  plus exposure to Geoport’s capabilities thanks to the hackers spamming of their decompiling efforts. So it’s a good win. 

I am sure people don’t appreciate the effort that went into building this.

 Everyone wants something for “free”.  No one wants to say thank you
