### ISSUE TITLE
Error loading Python lib for release 1.0.2

### ISSUE THREAD

**Issue by em1l1o** [davesc63/GeoPort#5]
Hi I have problem executing run.sh on my MacOS 10.15.7

Would be nice if you can take a look at it : )

<img width="952" alt="image" src="https://github.com/davesc63/GeoPort/assets/29399098/3ffb9423-e9da-4788-9f0c-8af9eda6510a">

**Comment by davesc63** [comment]
Thanks @em1l1o 
Can you please tell me the details / screenshot of your "About this mac" screen.

**Comment by em1l1o** [comment]
@davesc63 Hi sure!
<img width="480" alt="image" src="https://github.com/davesc63/GeoPort/assets/29399098/ffabdbe0-a514-4363-a31d-af04521f9510">

**Comment by em1l1o** [comment]
@davesc63 Hi sure!
<img width="261" alt="image" src="https://github.com/davesc63/GeoPort/assets/29399098/2dcdf84c-3e5b-4c2d-a1f0-c088dd5c0750">

**Comment by davesc63** [comment]
This issue here is with the "mininum version supported" by python.
This is external to GeoPort and currently with the version of Python being used - it does not support versions below MacOS 11.1

Current option is to upgrade to a new MacOS version

Alternative option, but not a priority, is looking to see if I can use a lower version of python for these older OS's
