### ISSUE TITLE
internet issue after connecting to geoport

### ISSUE THREAD

**Issue by nsk8r** [davesc63/GeoPort#72]
I have used geoport but due to some it didn't work and now my wifi is connected but no internet working,i am using mac bigsur, can you please advise if you anything.

**Comment by davesc63** [comment]
Not really sure what you’re asking. Nothing has changed in close to 2 months since the v2.3.3 releaseInternet access is not touched by GeoPortOn 27 Jun 2024, at 7:59 PM, nsk8r ***@***.***> wrote:﻿
I have used geoport but due to some it didn't work and now my wifi is connected but no internet working,i am using mac bigsur, can you please advise if you anything.

**Comment by nsk8r** [comment]
So I have connected geoport yesterday morning but somehow it didn’t go
through after local host link but unfortunately now my wifi shows connected
but internet is not working. I think some coding is still running in
backround that I can’t figure it out through terminal

**Comment by davesc63** [comment]
Please explain in more detail if you require help. Send the GeoPort log or screenshots. With the information you’ve shared… I cannot help youAgain, GeoPort does nothing to impact your internet accessOn 27 Jun 2024, at 8:06 PM, nsk8r ***@***.***> wrote:﻿
So I have connected geoport yesterday morning but somehow it didn’t go

through after local host link but unfortunately now my wifi shows connected

but internet is not working. I think some coding is still running in

backround that I can’t figure it out through terminal
