### ISSUE TITLE
map plugin can't load,can i input a location directly or change the map plugin?

### ISSUE THREAD

**Issue by littlestar2125** [davesc63/GeoPort#90]
Hello, the map plugin isn't loading. I've tried other methods, such as using a proxy and changing the Wi-Fi, but they didn't work. Can I input the location directly or change the map plugin? I believe the map is necessary for selecting the location. When I directly input the location, it alerts a NoneType error. Please help me. Apologies for my poor English.
![image](https://github.com/user-attachments/assets/4f45f8f5-ff94-4fc4-8bee-c1e6eb2a8623)

**Comment by davesc63** [comment]
Sorry to hear. This issue is either temporary if the map provider is unavailable, or it could be an issue with your connection to the map provider.

I would suggest looking at chrome devtools or similar to see if there are any errors reported by the browser.

It's not a GeoPort app issue, rather it would be a connectivity issue to the map provider (or the map provider themselves)

I have tested out GeoPort and the map is rendering for me.

**Comment by littlestar2125** [comment]
Can i change the map provider?Or i can directly input the location?
![image](https://github.com/user-attachments/assets/ae6804f9-a947-4be1-b91f-f21cd4d63f2a)
